In [1]:
import cv2
import matplotlib.pyplot as plt
import numpy as np

# Averaging Kernel

In [2]:
x=np.array([[6,7,4],[2,1,3],[9,5,4]])

In [3]:
x

array([[6, 7, 4],
       [2, 1, 3],
       [9, 5, 4]])

In [4]:
x.mean()

np.float64(4.555555555555555)

In [5]:
y=np.zeros([3,3])+1/9

In [6]:
y

array([[0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111]])

In [7]:
(x*y).sum()

np.float64(4.555555555555555)

In [8]:
img=cv2.imread("D:\\AshleshaRuchika\\PGCP-AI\\NLP\\images\\cat_damaged.png")
cv2.imshow("Image",img)

In [9]:
kernel=np.zeros([3,3])+1/9

In [10]:
kernel

array([[0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111]])

In [11]:
blurred_img=cv2.filter2D(img,-1,kernel)

In [ ]:
cv2.imshow('Blurred Image', blurred_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
kernel=np.zeros([9,9])+1/81
blurred_img=cv2.filter2D(img,-1,kernel)
img_new=np.hstack([img,blurred_img])
cv2.imshow('Blurred Image',img_new)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Gaussian Kernel

In [ ]:
kernel_size=7
kernel=cv2.getGaussianKernel(kernel_size,1.23)

In [ ]:
kernel

In [ ]:
gauss_image=cv2.filter2D(img,-1,kernel)
img_new=np.hstack([img,gauss_image])
cv2.imshow('Blurred Image', img_new)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Median Blue

In [ ]:
img_gray=cv2.imread("D:\\AshleshaRuchika\\PGCP-AI\\NLP\\images\\Dog2.png")
cv2.imshow("Dog",img_gray)

In [ ]:
img_gray.shape

In [ ]:
img_med=cv2.medianBlur(img_gray,7)

In [ ]:
plt.figure(figsize=(16,9))
plt.subplot(121)
plt.imshow(img_gray,cmap='gray')
plt.subplot(122)
plt.imshow(img_med,cmap='gray')

In [ ]:
img_med=cv2.medianBlur(img_gray[100:251,100:251],7)
img_copy=img_gray.copy()
img_copy[100:251,100:251]=img_med

In [ ]:
plt.figure(figsize=(16,9))
plt.subplot(121)
plt.imshow(img_gray,cmap='gray')
plt.subplot(122)
plt.imshow(img_copy,cmap='gray')