In [1]:
import numpy as np

In [2]:
arr_b = np.full(9, True).reshape(3,3)
arr_b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [3]:
arr = np.arange(3, 12).reshape(3,3)
arr

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [4]:
arr_odd =arr[arr%2!=0]
arr_odd

array([ 3,  5,  7,  9, 11])

In [5]:
arr[arr%2!=0]=-1
arr

array([[-1,  4, -1],
       [ 6, -1,  8],
       [-1, 10, -1]])

In [6]:
arr[:,::-1]

array([[-1,  4, -1],
       [ 8, -1,  6],
       [-1, 10, -1]])

In [7]:
arr

array([[-1,  4, -1],
       [ 6, -1,  8],
       [-1, 10, -1]])

In [8]:
index=np.where(arr>5)
index

(array([1, 1, 2]), array([0, 2, 1]))

In [9]:
index=np.argwhere(arr>5)
index

array([[1, 0],
       [1, 2],
       [2, 1]])

In [10]:
arr[-1:,-1:]

array([[-1]])

In [11]:
arr1 = np.full(25,1).reshape(5,5)
arr1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
arr1[1:-1,1:-1]=0
arr1

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [18]:
arr2=np.random.randint(100,size=(5,5))
arr2

array([[64,  4, 34, 95, 10],
       [27, 34, 58, 55, 59],
       [51, 50, 84, 46, 69],
       [ 0, 30, 94, 25, 75],
       [51, 46, 17,  3, 32]], dtype=int32)

In [19]:
min(arr2)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()