In [1]:
import numpy as np

In [2]:
arr = np.array([1,3,4,5,8,7,2])
arr

array([1, 3, 4, 5, 8, 7, 2])

In [3]:
arr.astype(float)

array([1., 3., 4., 5., 8., 7., 2.])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr= np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr.ndim

1

In [7]:
arr.size

10

In [8]:
arr.shape

(10,)

In [9]:
arr.dtype

dtype('int64')

In [10]:
arr=arr.reshape(2,5)

In [11]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
arr.shape

(2, 5)

In [13]:
zeros = np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
ones = np.ones([3,4])
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
arr_b = np.full(9, True).reshape(3,3)
arr_b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [16]:
arr_r = np.random.random([3,3])
arr_r

array([[0.94466455, 0.84850758, 0.45584536],
       [0.74349423, 0.98756233, 0.41310881],
       [0.03799323, 0.80336536, 0.21314544]])

In [17]:
arr_rd = np.random.randint(5,15,12)
arr_rd

array([10,  9,  5,  8,  5, 11, 11,  8, 11,  9, 13,  9], dtype=int32)

In [18]:
arr_l = np.linspace(2,20,10)
arr_l

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [19]:
empty_a = np.empty([2,3])
empty_a

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [2.11394070e-307, 2.78145267e-307, 6.95188863e-310]])

In [20]:
id_a = np.identity(3)
id_a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
arr = np.array([2,3])
arr

array([2, 3])

In [22]:
np.tile(arr, 2)

array([2, 3, 2, 3])

In [23]:
np.tile(arr, (2,3))

array([[2, 3, 2, 3, 2, 3],
       [2, 3, 2, 3, 2, 3]])

In [24]:
np.repeat(arr, (2,3))

array([2, 2, 3, 3, 3])