In [1]:
import numpy as np

In [2]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
for e in arr:
    print(e)

[0 1 2]
[3 4 5]
[6 7 8]


In [5]:
for i in np.nditer(arr):
    print(i)

0
1
2
3
4
5
6
7
8


In [6]:
np.ravel(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
arr1 = np.array([[1,2,3,4], [5,6,7,8]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr2=np.array([[11,12,13,14],[15,16,17,18]])
arr2

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [14]:
np.hstack([arr1,arr2])

array([[ 1,  2,  3,  4, 11, 12, 13, 14],
       [ 5,  6,  7,  8, 15, 16, 17, 18]])

In [15]:
np.vstack([arr1,arr2])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

In [16]:
np.repeat(arr,2)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8])

In [18]:
arr= np.array([2,3])
arr

array([2, 3])

In [19]:
np.repeat(arr, (1,2))

array([2, 3, 3])

In [20]:
arr= np.array([[2,3],[4,5]])
arr

array([[2, 3],
       [4, 5]])

In [22]:
np.repeat(arr,(1,2,2,3))

array([2, 3, 3, 4, 4, 5, 5, 5])

In [23]:
arr= np.array([2,3])
arr

array([2, 3])

In [24]:
np.tile(arr, 2)

array([2, 3, 2, 3])

In [25]:
arr

array([2, 3])

In [27]:
arr=np.insert(arr, 1, 4)
arr

array([2, 4, 3])

In [30]:
arr1=np.array([3,4])
np.concatenate([arr, arr1])

array([2, 4, 3, 3, 4])