In [1]:
import numpy as np

In [2]:
arr_1d = np.arange(10,18)
arr_1d

array([10, 11, 12, 13, 14, 15, 16, 17])

In [3]:
arr_1d[2]

np.int64(12)

In [4]:
arr_1d[-3]

np.int64(15)

In [5]:
arr_1d[2:7]

array([12, 13, 14, 15, 16])

In [6]:
arr_1d[:7]

array([10, 11, 12, 13, 14, 15, 16])

In [7]:
arr_1d[3:]

array([13, 14, 15, 16, 17])

In [8]:
arr_1d[::-1]

array([17, 16, 15, 14, 13, 12, 11, 10])

In [9]:
arr_1d[[1,4,7]]

array([11, 14, 17])

In [10]:
mask = arr_1d > 15
mask

array([False, False, False, False, False, False,  True,  True])

In [11]:
arr_1d[mask]

array([16, 17])

In [12]:
arr_1d[arr_1d > 15]

array([16, 17])

In [13]:
arr_1d[arr_1d %2==0]

array([10, 12, 14, 16])

In [14]:
arr_2d = np.arange(10,22).reshape(3,4)
arr_2d

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [15]:
arr_2d[1]

array([14, 15, 16, 17])

In [16]:
arr_2d[1,3]

np.int64(17)

In [17]:
arr_2d[0:2, 1:3]

array([[11, 12],
       [15, 16]])

In [18]:
arr_2d[::, :3]

array([[10, 11, 12],
       [14, 15, 16],
       [18, 19, 20]])

In [19]:
arr_2d[1:, 1:]

array([[15, 16, 17],
       [19, 20, 21]])

In [20]:
arr_2d[::-1]

array([[18, 19, 20, 21],
       [14, 15, 16, 17],
       [10, 11, 12, 13]])

In [21]:
arr_2d[arr_2d%2==1]

array([11, 13, 15, 17, 19, 21])

In [22]:
arr_2d[[True,False,True],[True,False,True,False]]

array([10, 20])

In [23]:
arr_2d[[True,False,True],[True,False,True,False]]

array([10, 20])

In [24]:
i_row = [0,2]
i_col = [1,3]
arr_2d[i_row, i_col]

array([11, 21])