In [1]:
import numpy as np


In [2]:
arr = np.array([[34,23,55],[70, 54,12]])
arr

array([[34, 23, 55],
       [70, 54, 12]])

In [3]:
arr.min()

np.int64(12)

In [4]:
arr.min(axis=0)

array([34, 23, 12])

In [5]:
arr.min(axis=1)

array([23, 12])

In [6]:
arr.max()

np.int64(70)

In [7]:
np.average(arr)

np.float64(41.333333333333336)

In [8]:
np.mean(arr)

np.float64(41.333333333333336)

In [9]:
np.median(arr)

np.float64(44.0)

In [10]:
np.std(arr)

np.float64(20.080393975772044)

In [11]:
np.var(arr)

np.float64(403.2222222222222)

In [12]:
np.sum(arr)

np.int64(248)

In [13]:
np.sum(arr, axis=0)

array([104,  77,  67])

In [14]:
np.sum(arr, axis=1)

array([112, 136])

In [15]:
np.prod(arr)

np.int64(1950933600)

In [16]:
np.cumsum(arr)

array([ 34,  57, 112, 182, 236, 248])

In [17]:
np.cumprod(arr)

array([        34,        782,      43010,    3010700,  162577800,
       1950933600])

In [18]:
np.percentile(arr,0)

np.float64(12.0)

In [19]:
np.percentile(arr,100)

np.float64(70.0)

In [20]:
np.percentile(arr,50)

np.float64(44.0)

In [21]:
arr = np.random.random([3,4])
arr

array([[0.67270615, 0.48473706, 0.63364158, 0.77962369],
       [0.65361863, 0.91966929, 0.99807353, 0.78545549],
       [0.06858713, 0.58222629, 0.35972046, 0.93551571]])

In [22]:
np.ceil(arr)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.floor(arr)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
arr = np.array([[34,23,55],[70, 54,12]])
arr

array([[34, 23, 55],
       [70, 54, 12]])

In [25]:
np.exp(arr)

array([[5.83461743e+14, 9.74480345e+09, 7.69478527e+23],
       [2.51543867e+30, 2.83075330e+23, 1.62754791e+05]])

In [26]:
np.sin(arr)

array([[ 0.52908269, -0.8462204 , -0.99975517],
       [ 0.77389068, -0.55878905, -0.53657292]])

In [27]:
np.power(arr, 2)

array([[1156,  529, 3025],
       [4900, 2916,  144]])

In [28]:
arr=np.log(arr)
arr

array([[3.52636052, 3.13549422, 4.00733319],
       [4.24849524, 3.98898405, 2.48490665]])

In [29]:
np.round(arr,2)

array([[3.53, 3.14, 4.01],
       [4.25, 3.99, 2.48]])