In [1]:
import numpy as np

In [2]:
arr =np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
arr.astype(float)

array([1., 2., 3., 4., 5., 6., 7.])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr.size

10

In [7]:
arr.shape

(10,)

In [8]:
arr.dtype

dtype('int64')

In [9]:
arr.ndim

1

In [10]:
arr = arr.reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
arr.shape

(2, 5)

In [12]:
zeros = np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
ones =np.ones([3,4])
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
arr_b =np.full(9,True).reshape(3,3)
arr_b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [15]:
arr_r =np.random.random([3,3])
arr_r

array([[0.1009491 , 0.53892103, 0.7524986 ],
       [0.73598233, 0.85083595, 0.80894023],
       [0.33476179, 0.01296815, 0.43087631]])

In [16]:
arr_rd =np.random.randint(5,15,12)
arr_rd

array([ 7,  5,  5,  7, 13,  9, 13,  6,  5,  5,  5,  9], dtype=int32)

In [17]:
arr_l = np.linspace(2,20,10)
arr_l

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [18]:
empty_a =np.empty([2,3])
empty_a

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [2.11394070e-307, 2.78145267e-307, 0.00000000e+000]])

In [19]:
id_a =np.identity(3)
id_a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])