In [9]:
import numpy as np

In [10]:
arr = np.array([1,2,2,3,4])
arr

array([1, 2, 2, 3, 4])

In [11]:
lst=[1,2,3,5]

In [12]:
print(arr*2)

[2 4 4 6 8]


In [15]:
import time
start_time=time.time()
print(arr+5)
end_time=time.time()
execution_time=end_time-start_time
print(f'\nExecution time: {execution_time}seconds')
print([x+5 for x in lst])

[6 7 7 8 9]

Execution time: 0.0005123615264892578seconds
[6, 7, 8, 10]


In [19]:
start_time=time.time()
print([x+5 for x in lst])
end_time=time.time()
execution_time=end_time-start_time
print(f'\nExecution time: {execution_time}seconds')


[6, 7, 8, 10]

Execution time: 0.0002827644348144531seconds


In [16]:
print(arr*2)
print([x*2 for x in lst])

[2 4 4 6 8]
[2, 4, 6, 10]


In [17]:
print(arr**2)
print([x**2 for x in lst])

[ 1  4  4  9 16]
[1, 4, 9, 25]


In [18]:
print(np.mean(arr))
print(sum(lst)/len(lst))

2.4
2.75


In [21]:
print(arr[arr%2==0])
print([x for x in lst if x%2==0])

[2 2 4]
[2]


In [22]:
print(np.array([[1,2] ,[3,4]]))
print([[1,2],[3,4]])

[[1 2]
 [3 4]]
[[1, 2], [3, 4]]


In [23]:
a= np.array([3,4,5])
b= np.array([5,6,8])
print(a+b)

[ 8 10 13]


In [24]:
x= [2,5,7]
y=[8,9,5]
print([a+b for a,b in zip(x,y)])

[10, 14, 12]


In [25]:
#broadcasting
print(arr+1)

[2 3 3 4 5]


In [26]:
#conditional repalce
arr[arr>2]=0
print(arr)

[1 2 2 0 0]


In [29]:
lst1=[1,5,6,8]
print([0 if x>2 else x for x in lst1])

[1, 0, 0, 0]


In [31]:
#Basics Usage
a=np.arange(0,10,2)
b= np.linspace(0,10,5)
print("arange(0,10,2)=",a)
print("linspace(0,10,5)=",b)

arange(0,10,2)= [0 2 4 6 8]
linspace(0,10,5)= [ 0.   2.5  5.   7.5 10. ]


In [32]:
#float behvaiour
print("\narange with float step(may miss endpoint):")
print(np.arange(0,1,0.2))
print("\narange with exact number of points:")
print(np.linspace(0,1,6))


arange with float step(may miss endpoint):
[0.  0.2 0.4 0.6 0.8]

arange with exact number of points:
[0.  0.2 0.4 0.6 0.8 1. ]


In [33]:
#endpoint control
print("\nlinspace without endpoint:")
print(np.linspace(0,10,5,endpoint=False))


linspace without endpoint:
[0. 2. 4. 6. 8.]


In [34]:
#length comparison
print("\nNumber of elements:")
print("len(arange):",len(np.arange(0,10,2)))
print("len(linspace):",len(np.linspace(0,10,5)))


Number of elements:
len(arange): 5
len(linspace): 5


In [36]:
#precision demonstration
print("\nPrecision check:")
arr =np.arange(0,1,0.1)
lin= np.linspace(0,1,10)
print("arange:",arr)
print("linspace:",lin)


Precision check:
arange: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
linspace: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [37]:
#filterating
arr2=np.arange(55,65)
print("original Array:\n",arr2)

original Array:
 [55 56 57 58 59 60 61 62 63 64]


In [38]:
#apply condition
mask= arr2>58
print("\nCondition(arr>58):\n",mask)


Condition(arr>58):
 [False False False False  True  True  True  True  True  True]


In [39]:
#boolean mask
print("\nBoolean Mask(true values will be selected):\n",mask)


Boolean Mask(true values will be selected):
 [False False False False  True  True  True  True  True  True]


In [40]:
#filtered values
filtered= arr2[mask]
print("\nFiltered Values(>58):\n",filtered)


Filtered Values(>58):
 [0.4 0.5 0.6 0.7 0.8 0.9]


In [46]:
#Direct filtering 
print("\nDirect filtering :\n",arr2[arr2>58])


Direct filtering :
 [59 60 61 62 63 64]


In [43]:
#multiple condition
print("\nValues between 57 and 62\n", arr2[(arr2>57) & (arr2<63)])


Values between 57 and 62
 [58 59 60 61 62]


In [45]:
#students marks
marks=np.array([67 ,43 ,87, 27])
passed_boolean= marks>35
print(passed_boolean)
print(marks[passed_boolean])

[ True  True  True False]
[67 43 87]


In [47]:
#shallo copy vr deep copy
a= np.array([50, 60,70,90])
a

array([50, 60, 70, 90])

In [48]:
#shallow copy
b=a[0:5]
print("Original a:",a)
print("\nShallow copy b:",b)

Original a: [50 60 70 90]

Shallow copy b: [50 60 70 90]


In [49]:
b[0]= 667
print("\nAfter modifying b:")
print("a:",a)
print("b:",b)


After modifying b:
a: [667  60  70  90]
b: [667  60  70  90]


In [50]:
#deep copy
c=a.copy()
c[1]=657
print("\nnAfter modifying c:")
print("a:",a)
print("c:",c)


nAfter modifying c:
a: [667  60  70  90]
c: [667 657  70  90]
