In [ ]:
# Assignment-3
# Name: Ashlesha Tayade               Name: Ruchika Gaikwad
# PRN: 260240128008                   PRN: 260240128036

In [1]:
import pandas as pd
import numpy as np

In [2]:
# 1. Write a Pandas program to create and display a one-dimensional array-like
# object containing an array of data using Pandas module.
df=pd.Series([1,2,3,4,5])
df

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
# 2. Write a Pandas program to convert a Panda module Series to Python list
# and it's type.
list1=list(df)
print("List:",list1)

List: [1, 2, 3, 4, 5]


In [4]:
# 3. Write a Pandas program to add, subtract, multiple and divide two Pandas
# Series.

df1=pd.Series([2,3,4,4,7,6,8])
df2=pd.Series([5,4,6,7,3,2,3])

#add
add=df1+df2
print("Addition of Series:\n",add)

#substract
sub= df1-df2
print("\nSubstrction of series:\n",sub)

#multiply
multiply=df1*df2
print("\nMultiplication of Series:\n",multiply)

#division
division=df1/df2
print("\nDivision Of Series:\n",division)

Addition of Series:
 0     7
1     7
2    10
3    11
4    10
5     8
6    11
dtype: int64

Substrction of series:
 0   -3
1   -1
2   -2
3   -3
4    4
5    4
6    5
dtype: int64

Multiplication of Series:
 0    10
1    12
2    24
3    28
4    21
5    12
6    24
dtype: int64

Division Of Series:
 0    0.400000
1    0.750000
2    0.666667
3    0.571429
4    2.333333
5    3.000000
6    2.666667
dtype: float64


In [5]:
# 4. Write a Pandas program to compare the elements of the two Pandas Series.

series1 = pd.Series([2, 4, 6, 8, 10])
series2 = pd.Series([1, 3, 5, 8, 10])
print("Series 1:\n",series1)
print("\nSeries 2:\n",series2)
print("\nComparison Results:")
print("Equals:\n",series1 == series2)
print("\nGreater than:\n",series1 > series2)
print("\nLess than:\n",series1 < series2)


Series 1:
 0     2
1     4
2     6
3     8
4    10
dtype: int64

Series 2:
 0     1
1     3
2     5
3     8
4    10
dtype: int64

Comparison Results:
Equals:
 0    False
1    False
2    False
3     True
4     True
dtype: bool

Greater than:
 0     True
1     True
2     True
3    False
4    False
dtype: bool

Less than:
 0    False
1    False
2    False
3    False
4    False
dtype: bool


In [6]:
# 5. Write a Pandas program to convert a dictionary to a Pandas series.
dict={'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
print("Dict:",dict)
df=pd.Series(df)
print("Pandas Series:\n",df)

Dict: {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Pandas Series:
 0    1
1    2
2    3
3    4
4    5
dtype: int64


In [7]:
# 6. Write a Pandas program to convert a NumPy array to a Pandas series.
# Sample Series:
# NumPy array:
# [10 20 30 40 50]
# Converted Pandas series:
# 0 10
# 1 20
# 2 30
# 3 40
# 4 50
# dtype: int64
arr=np.array([4,6,7,5,89,24])
print("Numpy Array:",arr)
seri=pd.Series(arr)
print("Pandas Series:\n",seri)

Numpy Array: [ 4  6  7  5 89 24]
Pandas Series:
 0     4
1     6
2     7
3     5
4    89
5    24
dtype: int64


In [8]:
# 7. Write a Pandas program to change the data type of given a column or a Series.
df=pd.Series([100,200,"python",300.12,400])
print(df)
floatType=pd.to_numeric(df, errors='coerce')
print(floatType)

0       100
1       200
2    python
3    300.12
4       400
dtype: object
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64


In [9]:
# 8. Write a Pandas program to convert the first column of a DataFrame as a Series.
data={"col1":[1,2,3,4,7,11],
     "col2":[4,5,6,9,5,7],
     "col3":[7,5,8,12,1,11]}

df=pd.DataFrame(data)
print("DataFrame: \n", df)

newSeries=pd.Series(df["col1"])
print("DataFrame as a Series: \n",newSeries)

DataFrame: 
    col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     7    11
DataFrame as a Series: 
 0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64


In [10]:
# 9. Write a Pandas program to convert a given Series to an array.

df=pd.Series([1,2,3,4,5,6,7,8,9])
print("DataFrame: \n",df)

arr=np.array(df)
print("\nArray: \n",arr)

DataFrame: 
 0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

Array: 
 [1 2 3 4 5 6 7 8 9]


In [11]:
# 10. Write a Pandas program to convert Series of lists to one Series.

data=pd.Series([['Red', 'Green', 'White'],['Red','Black'],['Yellow']])
print("Series:\n",data)
newList=data.explode().reset_index(drop=True)
print("\nList of one Series: \n",newList)

Series:
 0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object

List of one Series: 
 0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: str


In [12]:
# 11. Write a Pandas program to sort a given Series.
df=pd.Series(['100','200','300','python','300.12','400'])
df
sort_series=df.sort_values()
sort_series

0       100
1       200
2       300
4    300.12
5       400
3    python
dtype: str

In [13]:
# 12. Write a Pandas program to add some data to an existing Series.

df = pd.Series([100, 200, 300, 'python', 300.12, 400])
df1 = pd.Series([500, 'php'])
print("Series 1:\n",df)

newSeries = pd.concat([df, df1], ignore_index=True)
print("\nSeries 2:\n",newSeries)

Series 1:
 0       100
1       200
2       300
3    python
4    300.12
5       400
dtype: object

Series 2:
 0       100
1       200
2       300
3    python
4    300.12
5       400
6       500
7       php
dtype: object


In [15]:
# 13. Write a Pandas program to create a subset of a given series based on value and condition.

df=pd.Series([0,1,2,3,4,5,6,7,8,9,10])
print("Series:\n",df)

df1=df[df%2==0]
print("\nEven Numbers Subset Series: \n",df1)

Series:
 0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Even Numbers Subset Series: 
 0      0
2      2
4      4
6      6
8      8
10    10
dtype: int64


In [16]:
# 14. Write a Pandas program to change the order of index of a given series.

df=pd.Series([1,2,3,4,5,6], index=(['A','B','C','D','E','F']))
print("Series: \n",df)

s_new = df.reindex(index=['B', 'A', 'C', 'D', 'E'])
print("\nData Series after changing the order of index: \n",s_new)

Series: 
 A    1
B    2
C    3
D    4
E    5
F    6
dtype: int64

Data Series after changing the order of index: 
 B    2
A    1
C    3
D    4
E    5
dtype: int64


In [17]:
# 15. Write a Pandas program to create the mean and standard deviation of the data of a given Series.

df =pd.Series([1,3,4,7,8,9,3,4])
print("Original series:\n",df)
df.mean()
print("\nMean:",df.mean())
df.std()
print("\nStandard Deviation:",df.std())

Original series:
 0    1
1    3
2    4
3    7
4    8
5    9
6    3
7    4
dtype: int64

Mean: 4.875

Standard Deviation: 2.799872446074234


In [18]:
# 16. Write a Pandas program to get the items of a given series not present in another given series.

sr1=pd.Series([1,2,3,4,5])
sr2=pd.Series([2,4,6,8,10])
print("Series 1: \n",sr1)
print("\nSeries 2: \n",sr2)

new_series=sr1[~sr1.isin(sr2)]
print("\nItems of sr1 not present in sr2: \n",new_series)

Series 1: 
 0    1
1    2
2    3
3    4
4    5
dtype: int64

Series 2: 
 0     2
1     4
2     6
3     8
4    10
dtype: int64

Items of sr1 not present in sr2: 
 0    1
2    3
4    5
dtype: int64


In [19]:
# 17. Write a Pandas program to get the items which are not common of two given series.

sr1=pd.Series([1,2,3,4,5])
sr2=pd.Series([2,4,6,8,10])
print("Series 1: \n",sr1)
print("\nSeries 2: \n",sr2)

sr_union = pd.Series(pd.concat([sr1, sr2]))
sr_intersection = pd.Series(list(set(sr1) & set(sr2)))

new_series=sr_union[~sr_union.isin(sr_intersection)]
print("\nItems of a given series not present in another given series:\n", new_series)

Series 1: 
 0    1
1    2
2    3
3    4
4    5
dtype: int64

Series 2: 
 0     2
1     4
2     6
3     8
4    10
dtype: int64

Items of a given series not present in another given series:
 0     1
2     3
4     5
2     6
3     8
4    10
dtype: int64


In [20]:
# 18. Write a Pandas program to compute the minimum, 25th percentile, median, 75th, and maximum of a given series.
sr=pd.Series([3.000938,11.370722,14.612143,14.118931,8.247458,5.526727,4.766365,6.578372,2.637919,8.536117])
print("Series:\n",sr)

print("\nMinimum, 25th percentile, median, 75th, and maximum of a given series:")
result=np.percentile(sr, q=[0, 25, 50, 75, 100])
result

Series:
 0     3.000938
1    11.370722
2    14.612143
3    14.118931
4     8.247458
5     5.526727
6     4.766365
7     6.578372
8     2.637919
9     8.536117
dtype: float64

Minimum, 25th percentile, median, 75th, and maximum of a given series:


array([ 2.637919  ,  4.9564555 ,  7.412915  , 10.66207075, 14.612143  ])

In [21]:
# 19. Write a Pandas program to calculate the frequency counts of each unique value of a given series.

df=pd.Series([1,2,3,3,4,6,7,3,4,1,3,5,6,9,8,7,6,4])
print("original Series:\n",df)
uniquevalue=df.value_counts()
print("\nFrequency Counts:\n",uniquevalue)


original Series:
 0     1
1     2
2     3
3     3
4     4
5     6
6     7
7     3
8     4
9     1
10    3
11    5
12    6
13    9
14    8
15    7
16    6
17    4
dtype: int64

Frequency Counts:
 3    4
4    3
6    3
1    2
7    2
2    1
5    1
9    1
8    1
Name: count, dtype: int64


In [22]:
# 20. Write a Pandas program to display most frequent value in a given series and replace everything else as 'Other' in the series.

sr1=pd.Series([1,4,3,4,5,4,4,4,4,2,1,2,2,2,7,8,9])
most_freq = sr1.value_counts().index[0]

result = sr1.mask(sr1 != most_freq, 'Other')

print("\nModified Series (Most frequent kept, others replaced):")
print(result)


Modified Series (Most frequent kept, others replaced):
0     Other
1         4
2     Other
3         4
4     Other
5         4
6         4
7         4
8         4
9     Other
10    Other
11    Other
12    Other
13    Other
14    Other
15    Other
16    Other
dtype: object


In [23]:
# 21. Write a Pandas program to find the positions of numbers that are multiples of 5 of a given series.
df= pd.Series([5,10,10,14,15,20,17,56,55,25,35,12])
print("Original Series:\n",df)
result = np.where(df % 5 == 0)[0]
print("\nPositions of numbers that are multiples of 5:")
print(result)


Original Series:
 0      5
1     10
2     10
3     14
4     15
5     20
6     17
7     56
8     55
9     25
10    35
11    12
dtype: int64

Positions of numbers that are multiples of 5:
[ 0  1  2  4  5  8  9 10]


In [24]:
# 22. Write a Pandas program to extract items at given positions of a given series.
Data=pd.Series([10,22,10,23,2,6,8,2,9])
print("Original Data:\n",Data)

Positions=[0,4,5,2,7,8]
results=Data.iloc[Positions]
print("\nResults:\n",results)

Original Data:
 0    10
1    22
2    10
3    23
4     2
5     6
6     8
7     2
8     9
dtype: int64

Results:
 0    10
4     2
5     6
2    10
7     2
8     9
dtype: int64


In [25]:
# 23. Write a Pandas program to get the positions of items of a given series in another given series.

sr1 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
sr2 = pd.Series([1, 3, 5, 7, 10])

print("Original Series 1:\n", sr1)
print("\nOriginal Series 2:\n", sr2)

result = np.where(sr1.isin(sr2))[0].tolist()
results=list(results)

print("\nPositions of items of series2 in series1:")
print(result)


Original Series 1:
 0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

Original Series 2:
 0     1
1     3
2     5
3     7
4    10
dtype: int64

Positions of items of series2 in series1:
[0, 2, 4, 6, 9]


In [26]:
# 24. Write a Pandas program convert the first and last character of each word to upper case in each word of a given series.
word= pd.Series(['php','python','java','javascript'])
print("Original Series:")
print(word)
newSeries= word.map(lambda x: x[0].upper() + x[1:-1] + x[-1].upper() if len(x) > 1 else x.upper())
print("\nNewseries:")
print(newSeries)

Original Series:
0           php
1        python
2          java
3    javascript
dtype: str

Newseries:
0           PhP
1        PythoN
2          JavA
3    JavascripT
dtype: str


In [27]:
# 25. Write a Pandas program to calculate the number of characters in each word in a given series.

word= pd.Series(['php','python','java','javascript'])
print("Original Series:")
print(word)

LenWord=word.str.len()
print("\nNumber of characters in each word in the said series:")
print(LenWord)

Original Series:
0           php
1        python
2          java
3    javascript
dtype: str

Number of characters in each word in the said series:
0     3
1     6
2     4
3    10
dtype: int64


In [28]:
# 26. Write a Pandas program to compute difference of differences between consecutive numbers of a given series.
data = pd.Series([1, 3, 5, 8, 10, 11, 15])
print("Original Series:")
print(data)
first_diff = data.diff().tolist()
second_diff = data.diff().diff().tolist()
print("\nDifference of differences between consecutive numbers of the said series:")
print(first_diff)
print(second_diff)

Original Series:
0     1
1     3
2     5
3     8
4    10
5    11
6    15
dtype: int64

Difference of differences between consecutive numbers of the said series:
[nan, 2.0, 2.0, 3.0, 2.0, 1.0, 4.0]
[nan, nan, 0.0, 1.0, -1.0, -1.0, 3.0]


In [29]:
# 27. Write a Pandas program to convert a series of date strings to a timeseries.
date_strings_series=pd.Series(['01 Jan 2015','10-02-2016','20180307','2014/05/06','2016-04-12','2019-04-06T11:20'])
print(date_strings_series)
timeseries= pd.to_datetime(date_strings_series,format="mixed",dayfirst=True)

print("\nSeries of date strings to a timeseries:")
print(timeseries) 

0         01 Jan 2015
1          10-02-2016
2            20180307
3          2014/05/06
4          2016-04-12
5    2019-04-06T11:20
dtype: str

Series of date strings to a timeseries:
0   2015-01-01 00:00:00
1   2016-02-10 00:00:00
2   2018-07-03 00:00:00
3   2014-06-05 00:00:00
4   2016-12-04 00:00:00
5   2019-06-04 11:20:00
dtype: datetime64[us]


In [29]:
# 28. Write a Pandas program to get the day of month, day of year, week number and day
# of week from a given series of date strings
date_strings =['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20']
sr = pd.Series(date_strings)

ts = pd.to_datetime(sr, format='mixed', dayfirst=True)

print("Original Series:")
print(sr)

print("\nDay of month:")
print(ts.dt.day.tolist())

print("\nDay of year:")
print(ts.dt.dayofyear.tolist())

print("\nWeek number:")
print(ts.dt.isocalendar().week.tolist())

print("\nDay of week:")
print(ts.dt.day_name().tolist())

Original Series:
0         01 Jan 2015
1          10-02-2016
2            20180307
3          2014/05/06
4          2016-04-12
5    2019-04-06T11:20
dtype: str

Day of month:
[1, 10, 3, 5, 4, 4]

Day of year:
[1, 41, 184, 156, 339, 155]

Week number:
[1, 6, 27, 23, 48, 23]

Day of week:
['Thursday', 'Wednesday', 'Tuesday', 'Thursday', 'Sunday', 'Tuesday']


In [31]:
# 29. Write a Pandas program to convert year-month string to dates adding a specified day of the month.

sr = pd.Series(['Jan 2015', 'Feb 2016', 'Mar 2017', 'Apr 2018', 'May 2019'])
print("Original Series:")
print(sr)
day = '11'
result = pd.to_datetime(day + ' ' + sr)

print("\nNew dates:")
print(result)

Original Series:
0    Jan 2015
1    Feb 2016
2    Mar 2017
3    Apr 2018
4    May 2019
dtype: str

New dates:
0   2015-01-11
1   2016-02-11
2   2017-03-11
3   2018-04-11
4   2019-05-11
dtype: datetime64[us]


In [30]:
# 30. Write a Pandas program to filter words from a given series that contain atleast two
# vowels.
sr=pd.Series(["Red","Green","Orange","Pink","Yellow","White"])
sr1 = sr[sr.str.count(r'[aeiouAEIOU]') >= 2]
sr1

1     Green
2    Orange
4    Yellow
5     White
dtype: str

In [31]:
# 31. Write a Pandas program to compute the Euclidean distance between two given series.
# Euclidean distance
# From Wikipedia,
# In mathematics, the Euclidean distance or Euclidean metric is the "ordinary" straight-line
# distance between two points in Euclidean space. With this distance, Euclidean space
# becomes a metric space. The associated norm is called the Euclidean norm.

s1 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
s2 = pd.Series([11, 8, 7, 5, 6, 5, 3, 4, 7, 1])

print("Original series:")
print(s1)
print(s2)

# Method 1:
euclidean_dist = np.linalg.norm(s1 - s2)

# Method 2
# euclidean_dist = np.sqrt(np.sum((s1 - s2)**2))
print("\nEuclidean distance between two said series:")
print(euclidean_dist)

Original series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
0    11
1     8
2     7
3     5
4     6
5     5
6     3
7     4
8     7
9     1
dtype: int64

Euclidean distance between two said series:
16.492422502470642


In [32]:
# 32. Write a Pandas program to find the positions of the values neighboured by smaller
# values on both sides in a given series.

s = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])

print("Original series:")
print(s)

temp = np.where((s > s.shift(1)) & (s > s.shift(-1)))[0]

print("\nPositions of the values surrounded by smaller values on both sides:")
print(temp)


Original series:
0    1
1    8
2    7
3    5
4    6
5    5
6    3
7    4
8    7
9    1
dtype: int64

Positions of the values surrounded by smaller values on both sides:
[1 4 8]


In [33]:
# 33. Write a Pandas program to replace missing white spaces in a given string with the
# least frequent character.
str1 = 'abc def abcdef icd'
ser = pd.Series(list(str1))
freq = ser.value_counts()

least_freq_char = freq.drop(' ').idxmin()
result = str1.replace(' ', least_freq_char)

print("Original string:")
print(str1)
print("\nLeast frequent character:", least_freq_char)
print("\nResult:")
print(result)

Original string:
abc def abcdef icd

Least frequent character: i

Result:
abcidefiabcdefiicd


In [34]:
# 34. Write a Pandas program to compute the autocorrelations of a given numeric series.
# From Wikipedia:
# Autocorrelation, also known as serial correlation, is the correlation of a signal with a
# delayed copy of itself as a function of delay. Informally, it is the similarity between
# observations as a function of the time lag between them.
np.random.seed(42)
s = pd.Series(np.random.normal(10, 5, 15))

print("Original series:")
print(s)

autocorr_values = [round(s.autocorr(lag=i), 2) for i in range(1, 11)]

print("\nAutocorrelations of the said series:")
print(autocorr_values)

Original series:
0     12.483571
1      9.308678
2     13.238443
3     17.615149
4      8.829233
5      8.829315
6     17.896064
7     13.837174
8      7.652628
9     12.712800
10     7.682912
11     7.671351
12    11.209811
13     0.433599
14     1.375411
dtype: float64

Autocorrelations of the said series:
[np.float64(0.29), np.float64(-0.1), np.float64(0.65), np.float64(0.2), np.float64(-0.03), np.float64(0.28), np.float64(-0.45), np.float64(-0.33), np.float64(0.73), np.float64(-0.2)]


In [35]:
# 35. Write a Pandas program to create a TimeSeries to display all the Sundays of given
# year.
# Sample Output:]
sundays = pd.date_range(start='2019-01-01', end='2019-12-31', freq='W-SUN')
result = pd.Series(sundays)

print("All Sundays of 2019:")
print(result)

All Sundays of 2019:
0    2019-01-06
1    2019-01-13
2    2019-01-20
3    2019-01-27
4    2019-02-03
5    2019-02-10
6    2019-02-17
7    2019-02-24
8    2019-03-03
9    2019-03-10
10   2019-03-17
11   2019-03-24
12   2019-03-31
13   2019-04-07
14   2019-04-14
15   2019-04-21
16   2019-04-28
17   2019-05-05
18   2019-05-12
19   2019-05-19
20   2019-05-26
21   2019-06-02
22   2019-06-09
23   2019-06-16
24   2019-06-23
25   2019-06-30
26   2019-07-07
27   2019-07-14
28   2019-07-21
29   2019-07-28
30   2019-08-04
31   2019-08-11
32   2019-08-18
33   2019-08-25
34   2019-09-01
35   2019-09-08
36   2019-09-15
37   2019-09-22
38   2019-09-29
39   2019-10-06
40   2019-10-13
41   2019-10-20
42   2019-10-27
43   2019-11-03
44   2019-11-10
45   2019-11-17
46   2019-11-24
47   2019-12-01
48   2019-12-08
49   2019-12-15
50   2019-12-22
51   2019-12-29
dtype: datetime64[us]


In [36]:
# 36. Write a Pandas program to convert given series into a dataframe with its index as another column on the dataframe.
char_list = list('ABCDE')
s = pd.Series(char_list)

print("Original Series:")
print(s)
df = s.reset_index()
df.columns = ['index', '0']

print("\nSeries as a DataFrame with index as a column:")
print(df)

Original Series:
0    A
1    B
2    C
3    D
4    E
dtype: str

Series as a DataFrame with index as a column:
   index  0
0      0  A
1      1  B
2      2  C
3      3  D
4      4  E


In [37]:
# 37. Write a Pandas program to stack two given series vertically and horizontally.
s1 = pd.Series(range(10))
s2 = pd.Series(list('pqrstuvwxy'))

print("Original Series:")
print(s1)
print(s2)

vertical_stack = pd.concat([s1, s2], axis=0)
horizontal_stack = pd.concat([s1, s2], axis=1)

print("\nStack two given series vertically:")
print(vertical_stack)
print("\nStack two given series horizontally:")
print(horizontal_stack)

Original Series:
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64
0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
dtype: str

Stack two given series vertically:
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
dtype: object

Stack two given series horizontally:
   0  1
0  0  p
1  1  q
2  2  r
3  3  s
4  4  t
5  5  u
6  6  v
7  7  w
8  8  x
9  9  y


In [38]:
# 38. Write a Pandas program to check the equality of two given series.
s1 = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
s2 = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])

print("Original Series:")
print(s1)
print(s2)

result = (s1 == s2)

print("\nCheck 2 series are equal or not?")
print(result)

Original Series:
0    1
1    8
2    7
3    5
4    6
5    5
6    3
7    4
8    7
9    1
dtype: int64
0    1
1    8
2    7
3    5
4    6
5    5
6    3
7    4
8    7
9    1
dtype: int64

Check 2 series are equal or not?
0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
dtype: bool


In [39]:
# 39. Write a Pandas program to find the index of the first occurrence of the smallest and
# largest value of a given series.

s = pd.Series([1, 3, 7, 12, 15, 2, 5, 1, 9, 0])

print("Original Series:")
print(s)
smallest_idx = s.idxmin()
largest_idx = s.idxmax()

print("\nIndex of the first occurrence of the smallest and largest value of the said series:")
print(smallest_idx)
print(largest_idx)

Original Series:
0     1
1     3
2     7
3    12
4    15
5     2
6     5
7     1
8     9
9     0
dtype: int64

Index of the first occurrence of the smallest and largest value of the said series:
9
4


In [40]:
# 40. Write a Pandas program to check inequality over the index axis of a given dataframe
# and a given series.

df = pd.DataFrame({
    'W': [68.0, 75.0, 86.0, 80.0, np.nan],
    'X': [78.0, 75.0, np.nan, 80.0, 86.0],
    'Y': [84, 94, 89, 86, 86],
    'Z': [86, 97, 96, 72, 83]
})

s = pd.Series([68.0, 75.0, 86.0, 80.0, np.nan])

print("Original DataFrame:")
print(df)
print("\nOriginal Series:")
print(s)

result = df.ne(s, axis=0)

print("\nCheck for inequality of the said series & dataframe:")
print(result)

Original DataFrame:
      W     X   Y   Z
0  68.0  78.0  84  86
1  75.0  75.0  94  97
2  86.0   NaN  89  96
3  80.0  80.0  86  72
4   NaN  86.0  86  83

Original Series:
0    68.0
1    75.0
2    86.0
3    80.0
4     NaN
dtype: float64

Check for inequality of the said series & dataframe:
       W      X     Y     Z
0  False   True  True  True
1  False  False  True  True
2  False   True  True  True
3  False  False  True  True
4   True   True  True  True
